name: Build AVR Toolchain

on:
  workflow_call:

jobs:

  # Initial aarch64 build - produces both toolchain and target libs
  build-aarch64:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/jvasileff/avr-toolchain/avr-cross-builder:latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure Git Safe Directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Set Version Variables
      id: versions
      run: |
        . ./versions.sh
        echo "BUILD_VERSION=$BUILD_VERSION" | tee -a $GITHUB_OUTPUT
        echo "GCC_HOST=$GCC_HOST" | tee -a $GITHUB_OUTPUT

    - &cache-dependencies
      name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: build/download
        key: avr-dependencies-${{ hashFiles('checksums.txt') }}
        restore-keys: |
          avr-dependencies-
        enableCrossOsArchive: true

    - name: Build aarch64 Toolchain
      run: GCC_HOST=${{ steps.versions.outputs.GCC_HOST }} ./build-avr-toolchain.sh

    - name: Upload Toolchain Artifact
      uses: actions/upload-artifact@v4
      with:
        name: avr-toolchain-${{ steps.versions.outputs.BUILD_VERSION }}-${{ steps.versions.outputs.GCC_HOST }}.tar.xz
        path: build/artifacts/avr-toolchain-${{ steps.versions.outputs.BUILD_VERSION }}-${{ steps.versions.outputs.GCC_HOST }}.tar.xz
        compression-level: 0
        if-no-files-found: error

    - name: Upload Target Libs Artifact
      uses: actions/upload-artifact@v4
      with:
        name: avr-target-libs-${{ steps.versions.outputs.BUILD_VERSION }}.tar.xz
        path: build/artifacts/avr-target-libs-${{ steps.versions.outputs.BUILD_VERSION }}.tar.xz
        compression-level: 0
        if-no-files-found: error

  # Linux and Windows builds using Docker
  build-cross:
    needs: build-aarch64
    strategy:
      matrix:
        host:
          - aarch64-linux-musl
          - armv6-linux-gnueabihf
          - armv6-linux-musleabihf
          - i686-linux-gnu
          - i686-w64-mingw32
          - x86_64-linux-gnu
          - x86_64-linux-musl
          - x86_64-w64-mingw32

    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/jvasileff/avr-toolchain/avr-cross-builder:latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure Git Safe Directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Set Version Variables
      id: versions
      run: |
        . ./versions.sh
        echo "BUILD_VERSION=$BUILD_VERSION" | tee -a $GITHUB_OUTPUT
        echo "NATIVE_GCC_HOST=$GCC_HOST" | tee -a $GITHUB_OUTPUT
        echo "GCC_HOST=${{ matrix.host }}" | tee -a $GITHUB_OUTPUT
        case "${{ matrix.host }}" in
          *mingw32*)
            echo "ARCHIVE_EXT=.zip" | tee -a $GITHUB_OUTPUT
            ;;
          *)
            echo "ARCHIVE_EXT=.tar.xz" | tee -a $GITHUB_OUTPUT
            ;;
        esac

    - *cache-dependencies

    - name: Download Target Libs
      uses: actions/download-artifact@v4
      with:
        name: avr-target-libs-${{ steps.versions.outputs.BUILD_VERSION }}.tar.xz

    - name: Download Native Toolchain (aarch64)
      uses: actions/download-artifact@v4
      with:
        name: avr-toolchain-${{ steps.versions.outputs.BUILD_VERSION }}-${{ steps.versions.outputs.NATIVE_GCC_HOST }}.tar.xz

    - name: Build Toolchain
      run: |
        GCC_HOST=${{ steps.versions.outputs.GCC_HOST }} ./build-avr-toolchain.sh \
          --target-libs=avr-target-libs-${{ steps.versions.outputs.BUILD_VERSION }}.tar.xz \
          --native-avr-toolchain=avr-toolchain-${{ steps.versions.outputs.BUILD_VERSION }}-${{ steps.versions.outputs.NATIVE_GCC_HOST }}.tar.xz

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: avr-toolchain-${{ steps.versions.outputs.BUILD_VERSION }}-${{ steps.versions.outputs.GCC_HOST }}${{ steps.versions.outputs.ARCHIVE_EXT }}
        path: build/artifacts/avr-toolchain-${{ steps.versions.outputs.BUILD_VERSION }}-${{ steps.versions.outputs.GCC_HOST }}${{ steps.versions.outputs.ARCHIVE_EXT }}
        compression-level: 0
        if-no-files-found: error

  # macOS build
  build-macos:
    needs: build-aarch64
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure Git Safe Directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Set Version Variables
      id: versions
      run: |
        . ./versions.sh
        echo "BUILD_VERSION=$BUILD_VERSION" | tee -a $GITHUB_OUTPUT
        echo "GCC_HOST=$GCC_HOST" | tee -a $GITHUB_OUTPUT
        echo "ARCHIVE_EXT=.tar.xz" | tee -a $GITHUB_OUTPUT

    - *cache-dependencies

    - name: Install macOS Dependencies
      run: |
        brew install --quiet autoconf automake texinfo help2man

    - name: Download Target Libs
      uses: actions/download-artifact@v4
      with:
        name: avr-target-libs-${{ steps.versions.outputs.BUILD_VERSION }}.tar.xz

    - name: Build macOS Toolchain
      run: |
        ./build-avr-toolchain.sh \
          --target-libs=avr-target-libs-${{ steps.versions.outputs.BUILD_VERSION }}.tar.xz

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: avr-toolchain-${{ steps.versions.outputs.BUILD_VERSION }}-${{ steps.versions.outputs.GCC_HOST }}${{ steps.versions.outputs.ARCHIVE_EXT }}
        path: build/artifacts/avr-toolchain-${{ steps.versions.outputs.BUILD_VERSION }}-${{ steps.versions.outputs.GCC_HOST }}${{ steps.versions.outputs.ARCHIVE_EXT }}
        compression-level: 0
        if-no-files-found: error
