name: Build AVR Toolchain

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential texinfo automake python3 wget zip unzip

    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install autoconf automake

    - name: Build Toolchain
      run: ./build-avr-toolchain.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: avr-toolchain-${{ runner.os }}
        path: build/avr-toolchain/
        compression-level: 9