name: Build AVR Toolchain

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            host: x86_64-linux-gnu
          - os: macos-latest
            host: arm64-apple-darwin
          - os: macos-13
            host: x86_64-apple-darwin
          - os: ubuntu-24.04-arm
            host: aarch64-linux-gnu
          - os: ubuntu-24.04-arm
            host: arm-linux-gnueabihf

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set Version Variables
      id: versions
      run: echo "VERSION=$(.github/workflows/scripts/determine-version.js)" >> $GITHUB_OUTPUT

    - name: Install Linux Dependencies
      if: runner.os == 'Linux' && matrix.host != 'arm-linux-gnueabihf'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential texinfo automake autoconf python3 wget zip unzip bzip2

    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install --quiet autoconf automake

    - name: Build Toolchain
      if: matrix.host != 'arm-linux-gnueabihf'
      run: ./build-avr-toolchain.sh

    - name: Build Toolchain (armv7)
      if: matrix.host == 'arm-linux-gnueabihf'
      run: |
        docker run --platform linux/arm/v7 --rm -v ${{ github.workspace }}:/workspace arm32v7/ubuntu:22.04 \
          bash -c "\
            apt-get update && \
            apt-get install -y build-essential texinfo automake autoconf python3 wget zip unzip bzip2 && \
            cd /workspace && \
            ./build-avr-toolchain.sh"

    - name: Prepare Artifact Archive
      run: |
        cd build
        tar -cjf ../avr-toolchain-${{ steps.versions.outputs.VERSION }}-${{ matrix.host }}.tar.bz2 avr-toolchain

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: avr-toolchain-${{ steps.versions.outputs.VERSION }}-${{ matrix.host }}.tar.bz2
        path: avr-toolchain-${{ steps.versions.outputs.VERSION }}-${{ matrix.host }}.tar.bz2
        compression-level: 0
        if-no-files-found: error

  build-windows:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [i686-w64-mingw32, x86_64-w64-mingw32]

    steps:
    - uses: actions/checkout@v4

    - name: Set Version Variables
      id: versions
      run: echo "VERSION=$(.github/workflows/scripts/determine-version.js)" >> $GITHUB_OUTPUT

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential texinfo automake autoconf python3 wget zip unzip bzip2 mingw-w64

    - name: Download Linux Toolchain
      uses: actions/download-artifact@v4
      with:
        name: avr-toolchain-${{ steps.versions.outputs.VERSION }}-x86_64-linux-gnu.tar.bz2

    - name: Extract Linux Toolchain
      run: |
        mkdir -p build-native
        cd build-native
        tar xf ../avr-toolchain-*-x86_64-linux-gnu.tar.bz2

    - name: Build Windows Toolchain
      run: |
        export PATH=$PWD/build-native/avr-toolchain/bin:$PATH
        export GCC_HOST="${{ matrix.host }}"
        ./build-avr-toolchain.sh

    - name: Prepare Artifact Archive
      run: |
        cd build
        tar -cjf ../avr-toolchain-${{ steps.versions.outputs.VERSION }}-${{ matrix.host }}.tar.bz2 avr-toolchain

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: avr-toolchain-${{ steps.versions.outputs.VERSION }}-${{ matrix.host }}.tar.bz2
        path: avr-toolchain-${{ steps.versions.outputs.VERSION }}-${{ matrix.host }}.tar.bz2
        compression-level: 0
        if-no-files-found: error