name: Create Release

on:
  push:
    tags:
      - 'v*.*.*_*'

jobs:
  build:
    uses: ./.github/workflows/build-avr-toolchain.yml

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
          pattern: avr-toolchain*

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          artifacts=(artifacts/*.tar.bz2)
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes \
            "${artifacts[@]}"
